// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './http';
import { client } from './client';
import type { GetGasData, GetGasHistoryData, GetGasHistoryResponses, GetGasResponses, GetProvidersData, GetProvidersErrors, GetProvidersResponses, GetSwapFromData, GetSwapFromErrors, GetSwapFromResponses, GetSwapToData, GetSwapToErrors, GetSwapToResponses, GetTokensData, GetTokensErrors, GetTokensResponses, PostChainflipBrokerChannelData, PostChainflipBrokerChannelResponses, PostPriceCachedPriceData, PostPriceCachedPriceResponses, PostScreenData, PostScreenErrors, PostScreenResponses, PostTrackData, PostTrackResponses, PostV3QuoteData, PostV3QuoteErrors, PostV3QuoteResponses, PostV3SwapData, PostV3SwapErrors, PostV3SwapResponses } from './types';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getProviders = <ThrowOnError extends boolean = false>(options?: Options<GetProvidersData, ThrowOnError>) => (options?.client ?? client).get<GetProvidersResponses, GetProvidersErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/providers',
    ...options
});

export const getTokens = <ThrowOnError extends boolean = false>(options?: Options<GetTokensData, ThrowOnError>) => (options?.client ?? client).get<GetTokensResponses, GetTokensErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/tokens',
    ...options
});

export const getSwapTo = <ThrowOnError extends boolean = false>(options: Options<GetSwapToData, ThrowOnError>) => (options.client ?? client).get<GetSwapToResponses, GetSwapToErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/swapTo',
    ...options
});

export const getSwapFrom = <ThrowOnError extends boolean = false>(options: Options<GetSwapFromData, ThrowOnError>) => (options.client ?? client).get<GetSwapFromResponses, GetSwapFromErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/swapFrom',
    ...options
});

export const postChainflipBrokerChannel = <ThrowOnError extends boolean = false>(options: Options<PostChainflipBrokerChannelData, ThrowOnError>) => (options.client ?? client).post<PostChainflipBrokerChannelResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/chainflip/broker/channel',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postTrack = <ThrowOnError extends boolean = false>(options?: Options<PostTrackData, ThrowOnError>) => (options?.client ?? client).post<PostTrackResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/track',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postScreen = <ThrowOnError extends boolean = false>(options: Options<PostScreenData, ThrowOnError>) => (options.client ?? client).post<PostScreenResponses, PostScreenErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/screen',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getGasHistory = <ThrowOnError extends boolean = false>(options?: Options<GetGasHistoryData, ThrowOnError>) => (options?.client ?? client).get<GetGasHistoryResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/gas/history',
    ...options
});

export const getGas = <ThrowOnError extends boolean = false>(options?: Options<GetGasData, ThrowOnError>) => (options?.client ?? client).get<GetGasResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/gas',
    ...options
});

export const postPriceCachedPrice = <ThrowOnError extends boolean = false>(options: Options<PostPriceCachedPriceData, ThrowOnError>) => (options.client ?? client).post<PostPriceCachedPriceResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/price/cached-price',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postV3Quote = <ThrowOnError extends boolean = false>(options: Options<PostV3QuoteData, ThrowOnError>) => (options.client ?? client).post<PostV3QuoteResponses, PostV3QuoteErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/v3/quote',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postV3Swap = <ThrowOnError extends boolean = false>(options: Options<PostV3SwapData, ThrowOnError>) => (options.client ?? client).post<PostV3SwapResponses, PostV3SwapErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/v3/swap',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
