// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './http';
import { client } from './client';
import type { CreateBrokerChannelData, CreateBrokerChannelResponses, ExecuteSwapData, ExecuteSwapErrors, ExecuteSwapResponses, GetCachedPriceData, GetCachedPriceResponses, GetGasHistoryData, GetGasHistoryResponses, GetGasPricesData, GetGasPricesResponses, GetProvidersData, GetProvidersErrors, GetProvidersResponses, GetQuoteData, GetQuoteErrors, GetQuoteResponses, GetSwapFromAssetsData, GetSwapFromAssetsErrors, GetSwapFromAssetsResponses, GetSwapToAssetsData, GetSwapToAssetsErrors, GetSwapToAssetsResponses, GetTokensData, GetTokensErrors, GetTokensResponses, ScreenAddressData, ScreenAddressErrors, ScreenAddressResponses, TrackTransactionData, TrackTransactionErrors, TrackTransactionResponses } from './types';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getProviders = <ThrowOnError extends boolean = false>(options?: Options<GetProvidersData, ThrowOnError>): RequestResult<GetProvidersResponses, GetProvidersErrors, ThrowOnError> => (options?.client ?? client).get<GetProvidersResponses, GetProvidersErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/providers',
    ...options
});

export const getTokens = <ThrowOnError extends boolean = false>(options?: Options<GetTokensData, ThrowOnError>): RequestResult<GetTokensResponses, GetTokensErrors, ThrowOnError> => (options?.client ?? client).get<GetTokensResponses, GetTokensErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/tokens',
    ...options
});

export const getSwapToAssets = <ThrowOnError extends boolean = false>(options: Options<GetSwapToAssetsData, ThrowOnError>): RequestResult<GetSwapToAssetsResponses, GetSwapToAssetsErrors, ThrowOnError> => (options.client ?? client).get<GetSwapToAssetsResponses, GetSwapToAssetsErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/swapTo',
    ...options
});

export const getSwapFromAssets = <ThrowOnError extends boolean = false>(options: Options<GetSwapFromAssetsData, ThrowOnError>): RequestResult<GetSwapFromAssetsResponses, GetSwapFromAssetsErrors, ThrowOnError> => (options.client ?? client).get<GetSwapFromAssetsResponses, GetSwapFromAssetsErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/swapFrom',
    ...options
});

export const createBrokerChannel = <ThrowOnError extends boolean = false>(options: Options<CreateBrokerChannelData, ThrowOnError>): RequestResult<CreateBrokerChannelResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateBrokerChannelResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/chainflip/broker/channel',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const trackTransaction = <ThrowOnError extends boolean = false>(options?: Options<TrackTransactionData, ThrowOnError>): RequestResult<TrackTransactionResponses, TrackTransactionErrors, ThrowOnError> => (options?.client ?? client).post<TrackTransactionResponses, TrackTransactionErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/track',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const screenAddress = <ThrowOnError extends boolean = false>(options: Options<ScreenAddressData, ThrowOnError>): RequestResult<ScreenAddressResponses, ScreenAddressErrors, ThrowOnError> => (options.client ?? client).post<ScreenAddressResponses, ScreenAddressErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/screen',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getGasPrices = <ThrowOnError extends boolean = false>(options?: Options<GetGasPricesData, ThrowOnError>): RequestResult<GetGasPricesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetGasPricesResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/gas',
    ...options
});

export const getGasHistory = <ThrowOnError extends boolean = false>(options?: Options<GetGasHistoryData, ThrowOnError>): RequestResult<GetGasHistoryResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetGasHistoryResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/gas/history',
    ...options
});

export const getCachedPrice = <ThrowOnError extends boolean = false>(options: Options<GetCachedPriceData, ThrowOnError>): RequestResult<GetCachedPriceResponses, unknown, ThrowOnError> => (options.client ?? client).post<GetCachedPriceResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/price',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getQuote = <ThrowOnError extends boolean = false>(options: Options<GetQuoteData, ThrowOnError>): RequestResult<GetQuoteResponses, GetQuoteErrors, ThrowOnError> => (options.client ?? client).post<GetQuoteResponses, GetQuoteErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/v3/quote',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const executeSwap = <ThrowOnError extends boolean = false>(options: Options<ExecuteSwapData, ThrowOnError>): RequestResult<ExecuteSwapResponses, ExecuteSwapErrors, ThrowOnError> => (options.client ?? client).post<ExecuteSwapResponses, ExecuteSwapErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/v3/swap',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
